version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=db_ecommerce
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      - REACT_URL=http://localhost
      # - DB_HOST=host.docker.internal
    ports:
      - 8000:8000
    expose:
      - 8000

  nginx:
    image: nginx:1.25.5
    ports:
      - 80:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      
# docker compose -p ecomemrce-reactjs-nodejs-mysql-nginx-docker up -d