version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=db_ecommerce
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'